//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumnoResponsable
    {
        public int id { get; set; }
        public Nullable<int> alumno_id { get; set; }
        public Nullable<int> responsable_id { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Responsable Responsable { get; set; }
    }
}
