//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int id { get; set; }
        public Nullable<int> alumno_id { get; set; }
        public Nullable<int> materia_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> presente { get; set; }
        public Nullable<int> grado_id { get; set; }
    
        public virtual Grado Grado { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Alumno Alumno { get; set; }
    }
}
