//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int id { get; set; }
        public Nullable<int> alumno_id { get; set; }
        public Nullable<int> materia_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<bool> presente { get; set; }
        public Nullable<int> grado_id { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
