//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteGradoMateria
    {
        public int id { get; set; }
        public Nullable<int> docente_id { get; set; }
        public Nullable<int> materia_id { get; set; }
        public Nullable<int> grado_id { get; set; }
        public Nullable<int> anio_escolar { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
