//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteGradoMateria
    {
        public int id { get; set; }
        public Nullable<int> docente_id { get; set; }
        public Nullable<int> materia_id { get; set; }
        public Nullable<int> grado_id { get; set; }
        public Nullable<int> anio_escolar { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
