//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITCAPlusEntities : DbContext
    {
        public ITCAPlusEntities()
            : base("name=ITCAPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<AlumnoResponsable> AlumnoResponsable { get; set; }
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<Docente> Docente { get; set; }
        public virtual DbSet<DocenteGradoMateria> DocenteGradoMateria { get; set; }
        public virtual DbSet<DocenteMateria> DocenteMateria { get; set; }
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<GradoAlumno> GradoAlumno { get; set; }
        public virtual DbSet<Notas> Notas { get; set; }
        public virtual DbSet<notiCambioNota> notiCambioNota { get; set; }
        public virtual DbSet<PeriodoEscolar> PeriodoEscolar { get; set; }
        public virtual DbSet<Responsable> Responsable { get; set; }
        public virtual DbSet<vw_AlumnosPorMateriaGrado> vw_AlumnosPorMateriaGrado { get; set; }
        public virtual DbSet<vw_ListadoAsistencia> vw_ListadoAsistencia { get; set; }
        public virtual DbSet<vw_MateriasAsignadasDocente> vw_MateriasAsignadasDocente { get; set; }
        public virtual DbSet<vw_NotasAnualesPorAlumno> vw_NotasAnualesPorAlumno { get; set; }
        public virtual DbSet<vw_NotasPorAlumno> vw_NotasPorAlumno { get; set; }
        public virtual DbSet<vw_PerfilDocente> vw_PerfilDocente { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
