//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notas
    {
        public int id { get; set; }
        public Nullable<int> alumno_id { get; set; }
        public Nullable<int> materia_id { get; set; }
        public Nullable<decimal> nota1 { get; set; }
        public Nullable<decimal> nota2 { get; set; }
        public Nullable<decimal> nota3 { get; set; }
        public string trimestres { get; set; }
        public Nullable<decimal> promedio { get; set; }
        public Nullable<int> anio_escolar { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
