//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notiCambioNota
    {
        public int id { get; set; }
        public int docente_id { get; set; }
        public string nombre_docente { get; set; }
        public int materia_id { get; set; }
        public string nombre_materia { get; set; }
        public int alumno_id { get; set; }
        public string nombre_alumno { get; set; }
        public string trimestres { get; set; }
        public bool permiso { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
    }
}
