//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notiCambioNota
    {
        public int id { get; set; }
        public int docente_id { get; set; }
        public string nombre_docente { get; set; }
        public int materia_id { get; set; }
        public string nombre_materia { get; set; }
        public int alumno_id { get; set; }
        public string nombre_alumno { get; set; }
        public string trimestres { get; set; }
        public bool permiso { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
    }
}
