//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoEscolar
    {
        public int id { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public Nullable<System.DateTime> primerEntregaNotas { get; set; }
        public Nullable<System.DateTime> segundaEntregaNotas { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
    }
}
