//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Docente = new HashSet<Docente>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string tel { get; set; }
        public string usuario { get; set; }
        public string correo { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> restablecer { get; set; }
        public Nullable<bool> confirmar { get; set; }
        public string Token { get; set; }
        public byte[] fotografia { get; set; }
        public string rol { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docente> Docente { get; set; }
    }
}
