//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Docente = new HashSet<Docente>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio")]  
        public string nombre { get; set; }
        [Required(ErrorMessage = "El telefono es obligatorio")]
        public string tel { get; set; }
        [Required(ErrorMessage = "El usuario es obligatorio")]
        public string usuario { get; set; }
        [Required(ErrorMessage = "El correo es obligatorio")]
        public string correo { get; set; }
        [Required(ErrorMessage = "La contraseña es obligatoria")]
        public string contrasena { get; set; }
        public Nullable<bool> restablecer { get; set; }
        public Nullable<bool> confirmar { get; set; }
        public string Token { get; set; }
        public byte[] fotografia { get; set; }
        public string rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docente> Docente { get; set; }
    }
}
