//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ListadoAsistencia
    {
        public string grado { get; set; }
        public string materia { get; set; }
        public string docente { get; set; }
        public string carnet { get; set; }
        public string alumno { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
    }
}
