//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MateriasAsignadasDocente
    {
        public int docente_id { get; set; }
        public string docente_nombre { get; set; }
        public int materia_id { get; set; }
        public string materia_nombre { get; set; }
        public int grado_id { get; set; }
        public string grado_nombre { get; set; }
        public Nullable<byte> nivel { get; set; }
        public Nullable<int> anio_escolar { get; set; }
    }
}
