//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MateriasAsignadasDocente
    {
        public int docente_id { get; set; }
        public string docente_nombre { get; set; }
        public int materia_id { get; set; }
        public string materia_nombre { get; set; }
        public int grado_id { get; set; }
        public string grado_nombre { get; set; }
        public Nullable<byte> nivel { get; set; }
        public Nullable<int> anio_escolar { get; set; }
    }
}
