//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NotasAnualesPorAlumno
    {
        public int alumno_id { get; set; }
        public string carnet { get; set; }
        public string alumno { get; set; }
        public string materia { get; set; }
        public string grado { get; set; }
        public string anio_escolar { get; set; }
        public Nullable<decimal> Trimestre1 { get; set; }
        public Nullable<decimal> Trimestre2 { get; set; }
        public Nullable<decimal> Trimestre3 { get; set; }
        public Nullable<decimal> PromedioFinal { get; set; }
    }
}
