//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PerfilDocente
    {
        public int docente_id { get; set; }
        public int usuario_id { get; set; }
        public string nombre_docente { get; set; }
        public string telefono { get; set; }
        public string carnet { get; set; }
        public string correo { get; set; }
        public bool estado { get; set; }
        public string rol { get; set; }
        public string especialidad { get; set; }
        public byte[] fotografia { get; set; }
    }
}
