//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PerfilDocente
    {
        public int docente_id { get; set; }
        public int usuario_id { get; set; }
        public string nombre_docente { get; set; }
        public string telefono { get; set; }
        public string usuario_login { get; set; }
        public string correo { get; set; }
        public string rol { get; set; }
        public string especialidad { get; set; }
        public byte[] fotografia { get; set; }
    }
}
