//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus
{
    using System;
    using System.Collections.Generic;
    
<<<<<<<< HEAD:ITCA-Plus/Usuarios.cs
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Docente = new HashSet<Docente>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docente> Docente { get; set; }
========
    public partial class notiCambioNota
    {
        public int id { get; set; }
        public int docente_id { get; set; }
        public string nombre_docente { get; set; }
        public int materia_id { get; set; }
        public string nombre_materia { get; set; }
        public int alumno_id { get; set; }
        public string nombre_alumno { get; set; }
        public string trimestres { get; set; }
        public bool permiso { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
>>>>>>>> origin/Bryan2:ITCA-Plus/Models/notiCambioNota.cs
    }
}
