//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITCA_Plus
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_NotasPorAlumno
    {
        public int nota_id { get; set; }
        public int alumno_id { get; set; }
        public string carnet { get; set; }
        public string alumno { get; set; }
        public string materia { get; set; }
        public string grado { get; set; }
        public string trimestres { get; set; }
        public Nullable<int> anio_escolar { get; set; }
        public Nullable<decimal> nota1 { get; set; }
        public Nullable<decimal> nota2 { get; set; }
        public Nullable<decimal> nota3 { get; set; }
        public Nullable<decimal> promedio { get; set; }
    }
}
